// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.24.3
// source: proto/gateway.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_Configure_FullMethodName             = "/gateway.GatewayService/Configure"
	GatewayService_OnHumanInputRequested_FullMethodName = "/gateway.GatewayService/OnHumanInputRequested"
	GatewayService_OnHumanInputResolved_FullMethodName  = "/gateway.GatewayService/OnHumanInputResolved"
	GatewayService_OnNotification_FullMethodName        = "/gateway.GatewayService/OnNotification"
	GatewayService_PostMessage_FullMethodName           = "/gateway.GatewayService/PostMessage"
	GatewayService_MessageToolSpec_FullMethodName       = "/gateway.GatewayService/MessageToolSpec"
	GatewayService_Shutdown_FullMethodName              = "/gateway.GatewayService/Shutdown"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayService is implemented by the gateway plugin. Squadron calls
// these methods to push events / configure / control the gateway.
type GatewayServiceClient interface {
	// Configure passes settings from HCL config plus a broker stream id
	// the gateway can use to dial back for SquadronService access.
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// OnHumanInputRequested is invoked when an agent calls the
	// builtins.human.ask tool. The gateway should surface the question
	// in its external system (Discord channel, Slack DM, etc).
	OnHumanInputRequested(ctx context.Context, in *HumanInputRecord, opts ...grpc.CallOption) (*Empty, error)
	// OnHumanInputResolved is invoked whenever a human-input request
	// transitions to resolved — including resolutions that came from
	// some other surface (commander, another gateway). The gateway
	// should update its external system to reflect the answer.
	OnHumanInputResolved(ctx context.Context, in *HumanInputRecord, opts ...grpc.CallOption) (*Empty, error)
	// OnNotification is invoked when a mission reaches a terminal state
	// (completed, failed, stopped) and the mission opted into gateway
	// notifications. The gateway posts an informational message to its
	// external system. Unlike human-input, notifications are one-way:
	// there is nothing for the user to act on.
	OnNotification(ctx context.Context, in *NotificationRecord, opts ...grpc.CallOption) (*Empty, error)
	// PostMessage posts a message to the gateway's external system. Squadron
	// exposes this to agents via the builtins.gateway.post tool. The payload
	// is the raw JSON the agent produced for the tool, matching the schema the
	// gateway advertised via MessageToolSpec — the gateway owns the message
	// contract (text, formatting, channel override, attachments, …) and parses
	// the payload itself.
	PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*Empty, error)
	// MessageToolSpec returns how the builtins.gateway.post tool should be
	// presented to the LLM for this gateway: a description (formatting docs)
	// and an optional JSON Schema for the tool's parameters. Squadron fetches
	// it once the gateway is up and builds the tool from it, so each gateway
	// can advertise exactly the rich-message shape it accepts.
	MessageToolSpec(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MessageToolSpecResponse, error)
	// Shutdown asks the gateway to release external resources cleanly
	// before squadron tears down the subprocess.
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, GatewayService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) OnHumanInputRequested(ctx context.Context, in *HumanInputRecord, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GatewayService_OnHumanInputRequested_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) OnHumanInputResolved(ctx context.Context, in *HumanInputRecord, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GatewayService_OnHumanInputResolved_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) OnNotification(ctx context.Context, in *NotificationRecord, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GatewayService_OnNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GatewayService_PostMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) MessageToolSpec(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MessageToolSpecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageToolSpecResponse)
	err := c.cc.Invoke(ctx, GatewayService_MessageToolSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GatewayService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
//
// GatewayService is implemented by the gateway plugin. Squadron calls
// these methods to push events / configure / control the gateway.
type GatewayServiceServer interface {
	// Configure passes settings from HCL config plus a broker stream id
	// the gateway can use to dial back for SquadronService access.
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// OnHumanInputRequested is invoked when an agent calls the
	// builtins.human.ask tool. The gateway should surface the question
	// in its external system (Discord channel, Slack DM, etc).
	OnHumanInputRequested(context.Context, *HumanInputRecord) (*Empty, error)
	// OnHumanInputResolved is invoked whenever a human-input request
	// transitions to resolved — including resolutions that came from
	// some other surface (commander, another gateway). The gateway
	// should update its external system to reflect the answer.
	OnHumanInputResolved(context.Context, *HumanInputRecord) (*Empty, error)
	// OnNotification is invoked when a mission reaches a terminal state
	// (completed, failed, stopped) and the mission opted into gateway
	// notifications. The gateway posts an informational message to its
	// external system. Unlike human-input, notifications are one-way:
	// there is nothing for the user to act on.
	OnNotification(context.Context, *NotificationRecord) (*Empty, error)
	// PostMessage posts a message to the gateway's external system. Squadron
	// exposes this to agents via the builtins.gateway.post tool. The payload
	// is the raw JSON the agent produced for the tool, matching the schema the
	// gateway advertised via MessageToolSpec — the gateway owns the message
	// contract (text, formatting, channel override, attachments, …) and parses
	// the payload itself.
	PostMessage(context.Context, *PostMessageRequest) (*Empty, error)
	// MessageToolSpec returns how the builtins.gateway.post tool should be
	// presented to the LLM for this gateway: a description (formatting docs)
	// and an optional JSON Schema for the tool's parameters. Squadron fetches
	// it once the gateway is up and builds the tool from it, so each gateway
	// can advertise exactly the rich-message shape it accepts.
	MessageToolSpec(context.Context, *Empty) (*MessageToolSpecResponse, error)
	// Shutdown asks the gateway to release external resources cleanly
	// before squadron tears down the subprocess.
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedGatewayServiceServer) OnHumanInputRequested(context.Context, *HumanInputRecord) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnHumanInputRequested not implemented")
}
func (UnimplementedGatewayServiceServer) OnHumanInputResolved(context.Context, *HumanInputRecord) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnHumanInputResolved not implemented")
}
func (UnimplementedGatewayServiceServer) OnNotification(context.Context, *NotificationRecord) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnNotification not implemented")
}
func (UnimplementedGatewayServiceServer) PostMessage(context.Context, *PostMessageRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PostMessage not implemented")
}
func (UnimplementedGatewayServiceServer) MessageToolSpec(context.Context, *Empty) (*MessageToolSpecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MessageToolSpec not implemented")
}
func (UnimplementedGatewayServiceServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_OnHumanInputRequested_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HumanInputRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).OnHumanInputRequested(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_OnHumanInputRequested_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).OnHumanInputRequested(ctx, req.(*HumanInputRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_OnHumanInputResolved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HumanInputRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).OnHumanInputResolved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_OnHumanInputResolved_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).OnHumanInputResolved(ctx, req.(*HumanInputRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_OnNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).OnNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_OnNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).OnNotification(ctx, req.(*NotificationRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_PostMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).PostMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_PostMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).PostMessage(ctx, req.(*PostMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_MessageToolSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).MessageToolSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_MessageToolSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).MessageToolSpec(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configure",
			Handler:    _GatewayService_Configure_Handler,
		},
		{
			MethodName: "OnHumanInputRequested",
			Handler:    _GatewayService_OnHumanInputRequested_Handler,
		},
		{
			MethodName: "OnHumanInputResolved",
			Handler:    _GatewayService_OnHumanInputResolved_Handler,
		},
		{
			MethodName: "OnNotification",
			Handler:    _GatewayService_OnNotification_Handler,
		},
		{
			MethodName: "PostMessage",
			Handler:    _GatewayService_PostMessage_Handler,
		},
		{
			MethodName: "MessageToolSpec",
			Handler:    _GatewayService_MessageToolSpec_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _GatewayService_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gateway.proto",
}

const (
	SquadronService_ListHumanInputs_FullMethodName   = "/gateway.SquadronService/ListHumanInputs"
	SquadronService_ResolveHumanInput_FullMethodName = "/gateway.SquadronService/ResolveHumanInput"
)

// SquadronServiceClient is the client API for SquadronService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SquadronService is implemented by the host (squadron) and registered
// on a broker stream. Gateways dial it on startup to query / mutate
// state. Designed to grow over time — additional capabilities (mission
// listing, run, dataset queries, etc.) get appended here.
type SquadronServiceClient interface {
	// ListHumanInputs returns matching records. The `since` filter is
	// the primary catch-up mechanism: a gateway records the last event
	// timestamp it processed and asks for everything since.
	ListHumanInputs(ctx context.Context, in *HumanInputFilter, opts ...grpc.CallOption) (*HumanInputList, error)
	// ResolveHumanInput records an answer from the gateway's external
	// system. Idempotent — calling twice returns alreadyResolved=true
	// with the original resolution intact, never an error.
	ResolveHumanInput(ctx context.Context, in *ResolveHumanInputRequest, opts ...grpc.CallOption) (*ResolveHumanInputResponse, error)
}

type squadronServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSquadronServiceClient(cc grpc.ClientConnInterface) SquadronServiceClient {
	return &squadronServiceClient{cc}
}

func (c *squadronServiceClient) ListHumanInputs(ctx context.Context, in *HumanInputFilter, opts ...grpc.CallOption) (*HumanInputList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HumanInputList)
	err := c.cc.Invoke(ctx, SquadronService_ListHumanInputs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squadronServiceClient) ResolveHumanInput(ctx context.Context, in *ResolveHumanInputRequest, opts ...grpc.CallOption) (*ResolveHumanInputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveHumanInputResponse)
	err := c.cc.Invoke(ctx, SquadronService_ResolveHumanInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SquadronServiceServer is the server API for SquadronService service.
// All implementations must embed UnimplementedSquadronServiceServer
// for forward compatibility.
//
// SquadronService is implemented by the host (squadron) and registered
// on a broker stream. Gateways dial it on startup to query / mutate
// state. Designed to grow over time — additional capabilities (mission
// listing, run, dataset queries, etc.) get appended here.
type SquadronServiceServer interface {
	// ListHumanInputs returns matching records. The `since` filter is
	// the primary catch-up mechanism: a gateway records the last event
	// timestamp it processed and asks for everything since.
	ListHumanInputs(context.Context, *HumanInputFilter) (*HumanInputList, error)
	// ResolveHumanInput records an answer from the gateway's external
	// system. Idempotent — calling twice returns alreadyResolved=true
	// with the original resolution intact, never an error.
	ResolveHumanInput(context.Context, *ResolveHumanInputRequest) (*ResolveHumanInputResponse, error)
	mustEmbedUnimplementedSquadronServiceServer()
}

// UnimplementedSquadronServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSquadronServiceServer struct{}

func (UnimplementedSquadronServiceServer) ListHumanInputs(context.Context, *HumanInputFilter) (*HumanInputList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHumanInputs not implemented")
}
func (UnimplementedSquadronServiceServer) ResolveHumanInput(context.Context, *ResolveHumanInputRequest) (*ResolveHumanInputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveHumanInput not implemented")
}
func (UnimplementedSquadronServiceServer) mustEmbedUnimplementedSquadronServiceServer() {}
func (UnimplementedSquadronServiceServer) testEmbeddedByValue()                         {}

// UnsafeSquadronServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SquadronServiceServer will
// result in compilation errors.
type UnsafeSquadronServiceServer interface {
	mustEmbedUnimplementedSquadronServiceServer()
}

func RegisterSquadronServiceServer(s grpc.ServiceRegistrar, srv SquadronServiceServer) {
	// If the following call panics, it indicates UnimplementedSquadronServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SquadronService_ServiceDesc, srv)
}

func _SquadronService_ListHumanInputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HumanInputFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquadronServiceServer).ListHumanInputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquadronService_ListHumanInputs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquadronServiceServer).ListHumanInputs(ctx, req.(*HumanInputFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquadronService_ResolveHumanInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveHumanInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquadronServiceServer).ResolveHumanInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquadronService_ResolveHumanInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquadronServiceServer).ResolveHumanInput(ctx, req.(*ResolveHumanInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SquadronService_ServiceDesc is the grpc.ServiceDesc for SquadronService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SquadronService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.SquadronService",
	HandlerType: (*SquadronServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHumanInputs",
			Handler:    _SquadronService_ListHumanInputs_Handler,
		},
		{
			MethodName: "ResolveHumanInput",
			Handler:    _SquadronService_ResolveHumanInput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gateway.proto",
}
