// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.3
// source: proto/gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

type ConfigureRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Settings map[string]string      `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// BrokerStreamId is the broker stream the gateway should dial to
	// get a SquadronService client. Always non-zero.
	BrokerStreamId uint32 `protobuf:"varint,2,opt,name=broker_stream_id,json=brokerStreamId,proto3" json:"broker_stream_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigureRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ConfigureRequest) GetBrokerStreamId() uint32 {
	if x != nil {
		return x.BrokerStreamId
	}
	return 0
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HumanInputRecord mirrors the squadron-wire HumanInputRecord type.
// Kept here as a gRPC-friendly message so the SDK doesn't pull in the
// wire package's broader dependencies.
type HumanInputRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MissionId         string                 `protobuf:"bytes,2,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	MissionName       string                 `protobuf:"bytes,3,opt,name=mission_name,json=missionName,proto3" json:"mission_name,omitempty"`
	TaskId            string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskName          string                 `protobuf:"bytes,5,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	ToolCallId        string                 `protobuf:"bytes,6,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Question          string                 `protobuf:"bytes,7,opt,name=question,proto3" json:"question,omitempty"`
	ShortSummary      string                 `protobuf:"bytes,8,opt,name=short_summary,json=shortSummary,proto3" json:"short_summary,omitempty"`
	AdditionalContext string                 `protobuf:"bytes,9,opt,name=additional_context,json=additionalContext,proto3" json:"additional_context,omitempty"`
	Choices           []string               `protobuf:"bytes,10,rep,name=choices,proto3" json:"choices,omitempty"`
	State             string                 `protobuf:"bytes,11,opt,name=state,proto3" json:"state,omitempty"`                                // "open" | "resolved"
	RequestedAt       string                 `protobuf:"bytes,12,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"` // RFC3339Nano
	ResolvedAt        string                 `protobuf:"bytes,13,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`    // RFC3339Nano, empty if open
	Response          string                 `protobuf:"bytes,14,opt,name=response,proto3" json:"response,omitempty"`
	ResponderUserId   string                 `protobuf:"bytes,15,opt,name=responder_user_id,json=responderUserId,proto3" json:"responder_user_id,omitempty"`
	// multi_select=true means the human can pick 1+ from choices. The
	// resolved response is then a JSON-encoded array of strings
	// (e.g. `["A","C"]`) rather than a single value.
	MultiSelect   bool `protobuf:"varint,16,opt,name=multi_select,json=multiSelect,proto3" json:"multi_select,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumanInputRecord) Reset() {
	*x = HumanInputRecord{}
	mi := &file_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanInputRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanInputRecord) ProtoMessage() {}

func (x *HumanInputRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanInputRecord.ProtoReflect.Descriptor instead.
func (*HumanInputRecord) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *HumanInputRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HumanInputRecord) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *HumanInputRecord) GetMissionName() string {
	if x != nil {
		return x.MissionName
	}
	return ""
}

func (x *HumanInputRecord) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HumanInputRecord) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *HumanInputRecord) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *HumanInputRecord) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *HumanInputRecord) GetShortSummary() string {
	if x != nil {
		return x.ShortSummary
	}
	return ""
}

func (x *HumanInputRecord) GetAdditionalContext() string {
	if x != nil {
		return x.AdditionalContext
	}
	return ""
}

func (x *HumanInputRecord) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *HumanInputRecord) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HumanInputRecord) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

func (x *HumanInputRecord) GetResolvedAt() string {
	if x != nil {
		return x.ResolvedAt
	}
	return ""
}

func (x *HumanInputRecord) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *HumanInputRecord) GetResponderUserId() string {
	if x != nil {
		return x.ResponderUserId
	}
	return ""
}

func (x *HumanInputRecord) GetMultiSelect() bool {
	if x != nil {
		return x.MultiSelect
	}
	return false
}

type HumanInputFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // "open" | "resolved" | "" for both
	MissionId     string                 `protobuf:"bytes,2,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	Since         string                 `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"` // RFC3339Nano — match requested_at|resolved_at >= since
	OldestFirst   bool                   `protobuf:"varint,4,opt,name=oldest_first,json=oldestFirst,proto3" json:"oldest_first,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumanInputFilter) Reset() {
	*x = HumanInputFilter{}
	mi := &file_proto_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanInputFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanInputFilter) ProtoMessage() {}

func (x *HumanInputFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanInputFilter.ProtoReflect.Descriptor instead.
func (*HumanInputFilter) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *HumanInputFilter) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HumanInputFilter) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *HumanInputFilter) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *HumanInputFilter) GetOldestFirst() bool {
	if x != nil {
		return x.OldestFirst
	}
	return false
}

func (x *HumanInputFilter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *HumanInputFilter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type HumanInputList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*HumanInputRecord    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumanInputList) Reset() {
	*x = HumanInputList{}
	mi := &file_proto_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanInputList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanInputList) ProtoMessage() {}

func (x *HumanInputList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanInputList.ProtoReflect.Descriptor instead.
func (*HumanInputList) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *HumanInputList) GetItems() []*HumanInputRecord {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *HumanInputList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ResolveHumanInputRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId      string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Response        string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	ResponderUserId string                 `protobuf:"bytes,3,opt,name=responder_user_id,json=responderUserId,proto3" json:"responder_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResolveHumanInputRequest) Reset() {
	*x = ResolveHumanInputRequest{}
	mi := &file_proto_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveHumanInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveHumanInputRequest) ProtoMessage() {}

func (x *ResolveHumanInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveHumanInputRequest.ProtoReflect.Descriptor instead.
func (*ResolveHumanInputRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveHumanInputRequest) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ResolveHumanInputRequest) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ResolveHumanInputRequest) GetResponderUserId() string {
	if x != nil {
		return x.ResponderUserId
	}
	return ""
}

type ResolveHumanInputResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Record *HumanInputRecord      `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	// True when the request was already resolved before this call —
	// the record is the prior resolution, not a fresh one. Gateways
	// should treat this as success but display "already answered".
	AlreadyResolved bool `protobuf:"varint,2,opt,name=already_resolved,json=alreadyResolved,proto3" json:"already_resolved,omitempty"`
	// True when the tool_call_id is unknown to squadron entirely.
	// Gateways should treat this as a stale event (e.g. the row was
	// trimmed) rather than retry.
	NotFound      bool `protobuf:"varint,3,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveHumanInputResponse) Reset() {
	*x = ResolveHumanInputResponse{}
	mi := &file_proto_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveHumanInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveHumanInputResponse) ProtoMessage() {}

func (x *ResolveHumanInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveHumanInputResponse.ProtoReflect.Descriptor instead.
func (*ResolveHumanInputResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveHumanInputResponse) GetRecord() *HumanInputRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *ResolveHumanInputResponse) GetAlreadyResolved() bool {
	if x != nil {
		return x.AlreadyResolved
	}
	return false
}

func (x *ResolveHumanInputResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

// NotificationRecord describes a single mission-lifecycle notification.
// All fields are flat strings so the schema stays language-neutral.
type NotificationRecord struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MissionId   string                 `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	MissionName string                 `protobuf:"bytes,2,opt,name=mission_name,json=missionName,proto3" json:"mission_name,omitempty"`
	// event is one of "mission_completed", "mission_failed",
	// "mission_stopped".
	Event      string `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	Title      string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Message    string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	OccurredAt string `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // RFC3339Nano
	// error is set for "mission_failed", empty otherwise.
	Error string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	// channel is an optional per-mission destination override. When
	// empty the gateway posts to its globally configured default
	// channel.
	Channel string `protobuf:"bytes,8,opt,name=channel,proto3" json:"channel,omitempty"`
	// outputs_json is the JSON-encoded map of task name -> structured
	// output, populated for "mission_completed" only.
	OutputsJson   string `protobuf:"bytes,9,opt,name=outputs_json,json=outputsJson,proto3" json:"outputs_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRecord) Reset() {
	*x = NotificationRecord{}
	mi := &file_proto_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRecord) ProtoMessage() {}

func (x *NotificationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRecord.ProtoReflect.Descriptor instead.
func (*NotificationRecord) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *NotificationRecord) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *NotificationRecord) GetMissionName() string {
	if x != nil {
		return x.MissionName
	}
	return ""
}

func (x *NotificationRecord) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *NotificationRecord) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationRecord) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *NotificationRecord) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NotificationRecord) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *NotificationRecord) GetOutputsJson() string {
	if x != nil {
		return x.OutputsJson
	}
	return ""
}

var File_proto_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gateway.proto\x12\agateway\"\a\n" +
	"\x05Empty\"\xbe\x01\n" +
	"\x10ConfigureRequest\x12C\n" +
	"\bsettings\x18\x01 \x03(\v2'.gateway.ConfigureRequest.SettingsEntryR\bsettings\x12(\n" +
	"\x10broker_stream_id\x18\x02 \x01(\rR\x0ebrokerStreamId\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x11ConfigureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8b\x04\n" +
	"\x10HumanInputRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x02 \x01(\tR\tmissionId\x12!\n" +
	"\fmission_name\x18\x03 \x01(\tR\vmissionName\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_name\x18\x05 \x01(\tR\btaskName\x12 \n" +
	"\ftool_call_id\x18\x06 \x01(\tR\n" +
	"toolCallId\x12\x1a\n" +
	"\bquestion\x18\a \x01(\tR\bquestion\x12#\n" +
	"\rshort_summary\x18\b \x01(\tR\fshortSummary\x12-\n" +
	"\x12additional_context\x18\t \x01(\tR\x11additionalContext\x12\x18\n" +
	"\achoices\x18\n" +
	" \x03(\tR\achoices\x12\x14\n" +
	"\x05state\x18\v \x01(\tR\x05state\x12!\n" +
	"\frequested_at\x18\f \x01(\tR\vrequestedAt\x12\x1f\n" +
	"\vresolved_at\x18\r \x01(\tR\n" +
	"resolvedAt\x12\x1a\n" +
	"\bresponse\x18\x0e \x01(\tR\bresponse\x12*\n" +
	"\x11responder_user_id\x18\x0f \x01(\tR\x0fresponderUserId\x12!\n" +
	"\fmulti_select\x18\x10 \x01(\bR\vmultiSelect\"\xae\x01\n" +
	"\x10HumanInputFilter\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x02 \x01(\tR\tmissionId\x12\x14\n" +
	"\x05since\x18\x03 \x01(\tR\x05since\x12!\n" +
	"\foldest_first\x18\x04 \x01(\bR\voldestFirst\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"W\n" +
	"\x0eHumanInputList\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.gateway.HumanInputRecordR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x84\x01\n" +
	"\x18ResolveHumanInputRequest\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12*\n" +
	"\x11responder_user_id\x18\x03 \x01(\tR\x0fresponderUserId\"\x96\x01\n" +
	"\x19ResolveHumanInputResponse\x121\n" +
	"\x06record\x18\x01 \x01(\v2\x19.gateway.HumanInputRecordR\x06record\x12)\n" +
	"\x10already_resolved\x18\x02 \x01(\bR\x0falreadyResolved\x12\x1b\n" +
	"\tnot_found\x18\x03 \x01(\bR\bnotFound\"\x90\x02\n" +
	"\x12NotificationRecord\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\tR\tmissionId\x12!\n" +
	"\fmission_name\x18\x02 \x01(\tR\vmissionName\x12\x14\n" +
	"\x05event\x18\x03 \x01(\tR\x05event\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1f\n" +
	"\voccurred_at\x18\x06 \x01(\tR\n" +
	"occurredAt\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x18\n" +
	"\achannel\x18\b \x01(\tR\achannel\x12!\n" +
	"\foutputs_json\x18\t \x01(\tR\voutputsJson2\xc6\x02\n" +
	"\x0eGatewayService\x12B\n" +
	"\tConfigure\x12\x19.gateway.ConfigureRequest\x1a\x1a.gateway.ConfigureResponse\x12B\n" +
	"\x15OnHumanInputRequested\x12\x19.gateway.HumanInputRecord\x1a\x0e.gateway.Empty\x12A\n" +
	"\x14OnHumanInputResolved\x12\x19.gateway.HumanInputRecord\x1a\x0e.gateway.Empty\x12=\n" +
	"\x0eOnNotification\x12\x1b.gateway.NotificationRecord\x1a\x0e.gateway.Empty\x12*\n" +
	"\bShutdown\x12\x0e.gateway.Empty\x1a\x0e.gateway.Empty2\xb4\x01\n" +
	"\x0fSquadronService\x12E\n" +
	"\x0fListHumanInputs\x12\x19.gateway.HumanInputFilter\x1a\x17.gateway.HumanInputList\x12Z\n" +
	"\x11ResolveHumanInput\x12!.gateway.ResolveHumanInputRequest\x1a\".gateway.ResolveHumanInputResponseB/Z-github.com/mlund01/squadron-gateway-sdk/protob\x06proto3"

var (
	file_proto_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_proto_rawDescData []byte
)

func file_proto_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_proto_rawDescData
}

var file_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_gateway_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: gateway.Empty
	(*ConfigureRequest)(nil),          // 1: gateway.ConfigureRequest
	(*ConfigureResponse)(nil),         // 2: gateway.ConfigureResponse
	(*HumanInputRecord)(nil),          // 3: gateway.HumanInputRecord
	(*HumanInputFilter)(nil),          // 4: gateway.HumanInputFilter
	(*HumanInputList)(nil),            // 5: gateway.HumanInputList
	(*ResolveHumanInputRequest)(nil),  // 6: gateway.ResolveHumanInputRequest
	(*ResolveHumanInputResponse)(nil), // 7: gateway.ResolveHumanInputResponse
	(*NotificationRecord)(nil),        // 8: gateway.NotificationRecord
	nil,                               // 9: gateway.ConfigureRequest.SettingsEntry
}
var file_proto_gateway_proto_depIdxs = []int32{
	9,  // 0: gateway.ConfigureRequest.settings:type_name -> gateway.ConfigureRequest.SettingsEntry
	3,  // 1: gateway.HumanInputList.items:type_name -> gateway.HumanInputRecord
	3,  // 2: gateway.ResolveHumanInputResponse.record:type_name -> gateway.HumanInputRecord
	1,  // 3: gateway.GatewayService.Configure:input_type -> gateway.ConfigureRequest
	3,  // 4: gateway.GatewayService.OnHumanInputRequested:input_type -> gateway.HumanInputRecord
	3,  // 5: gateway.GatewayService.OnHumanInputResolved:input_type -> gateway.HumanInputRecord
	8,  // 6: gateway.GatewayService.OnNotification:input_type -> gateway.NotificationRecord
	0,  // 7: gateway.GatewayService.Shutdown:input_type -> gateway.Empty
	4,  // 8: gateway.SquadronService.ListHumanInputs:input_type -> gateway.HumanInputFilter
	6,  // 9: gateway.SquadronService.ResolveHumanInput:input_type -> gateway.ResolveHumanInputRequest
	2,  // 10: gateway.GatewayService.Configure:output_type -> gateway.ConfigureResponse
	0,  // 11: gateway.GatewayService.OnHumanInputRequested:output_type -> gateway.Empty
	0,  // 12: gateway.GatewayService.OnHumanInputResolved:output_type -> gateway.Empty
	0,  // 13: gateway.GatewayService.OnNotification:output_type -> gateway.Empty
	0,  // 14: gateway.GatewayService.Shutdown:output_type -> gateway.Empty
	5,  // 15: gateway.SquadronService.ListHumanInputs:output_type -> gateway.HumanInputList
	7,  // 16: gateway.SquadronService.ResolveHumanInput:output_type -> gateway.ResolveHumanInputResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_gateway_proto_init() }
func file_proto_gateway_proto_init() {
	if File_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_proto = out.File
	file_proto_gateway_proto_goTypes = nil
	file_proto_gateway_proto_depIdxs = nil
}
